---
- hosts: "{{ servidores }}"
  vars:
    nombre: joan
    empleado:
      nombre: pedro
      wiw: 10
      grupo: test
    empleados:
      - nombre: pedro
        wiw: 10
        grupo: test
      - nombre: marc
        wiw: 11
        group: dev
  tasks:
  - name: mostramos contenido de variable empleado
    debug:
      msg: 
      - "nombre: {{ nombre }}"
